Main/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from Account.views import Login, Register, activate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comment/', include('comment.urls')),
    path('', include('Nasa.urls')),
    path('', include('django.contrib.auth.urls')),
    path('Account/', include('Account.urls')),
    path("login/", Login.as_view(), name="login"),
    path('register', Register.as_view(), name='register'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Nasa/urls.py
from django.urls import path
from Nasa import views

app_name = 'Nasa'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about', views.About.as_view(), name='about'),
    path('contact', views.Contact.as_view(), name='contact'),
    path('post/', views.Post.as_view(), name='post'),
    path('Nasa/<slug:slug>', views.Nasa_Detail, name='Nasa-Detail'),
    path('search/', views.SearchBar.as_view(), name='search'),
    path('search/page/<int:page>', views.SearchBar.as_view(), name='search'),
]

comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

templates/WebSite/Nasa-Detail.html
{% extends 'WebSite/base.html' %}
{% load comment_tags %}
{% load static %}
{% block header %}
                <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'base/assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>{{ obj.Title }}</h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
{% endblock %}


{% block Main %}
<div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto text-justify">
   <h1><center style="margin-bottom: 25px">{{ obj.Title }}{% if obj.Is_Special %}
                                (<span style="color: red">ویژه</span>)
                            {% endif %}</center>
   </h1>
    <center> <img src="{{ obj.Image.url|safe }}" style="width: auto; height: 400px"> </center>
    <center>
        <div class="Nasa-Detail-Description">
        توضیحات :
        </div>
    </center>
    {% if obj.Is_Special %}
        {% if user.athenticated and user.Is_Special or user == obj.author or user.is_superuser %}
            <div style="padding: 70px">{{ obj.Description|safe }}</div>
            {% else %}
            <p>این پست ویژه است.<a href="#">اشتراک ویژه تهیه کنید</a></p>
        {% endif %}
    {% else %}
        <div style="padding: 70px">{{ obj.Description|safe }}</div>
    {% endif %}
        {% render_comments obj request %}
        {% include_bootstrap %}
        </div>
    </div>
</div>

{% endblock %}

templates/WebSite/about.html
{% extends 'WebSite/base.html' %}
{% load static %}
{% block Header %}
            <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'base/assets/img/Planets.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>درباره ما</h1>
                            <span class="subheading">↓</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
{% endblock %}
{% block Main %}
    <div style="padding: 40px">
    ادارهٔ کل ملی هوانوردی و فضا (به انگلیسی: National Aeronautics and Space Administration) به اختصار ناسا (به انگلیسی: NASA) سازمانی مستقل در قوهٔ مجریهٔ حکومت فدرال ایالات متحدهٔ آمریکا است که مسئولیت برنامه‌ریزی در حوزه‌های برنامهٔ فضایی کشوری و تحقیقات مکانیک پرواز و هوافضا را بر عهده دارد. در زمان جنگ سرد و پس از پرتاب ماهوارهٔ اسپوتنیک-۱ توسط اتحاد جماهیر شوروی سوسیالیستی به فضا، آمریکا به فکر ایجاد سازمان فضایی ملی خود افتاد و ناسا در ۲۹ ژوئیهٔ ۱۹۵۸ با امضای رئیس‌جمهور وقت دوایت آیزنهاور جای کمیتهٔ رایزنی ملی هوانوردی آمریکا (ناکا) را گرفت و بنیادگذاری شد. توماس کیت گلنان به عنوان نخستین مدیر ناسا و هیو لاتیمر درایدن به عنوان معاون او برگزیده شدند و فعالیت رسمی ناسا از ۱ اکتبر ۱۹۵۸ آغاز شد.

ناسا کار خود را با نورث امریکن ایکس-۱۵ آغاز کرد و هشت خلبان در این پروژه توانستند خود را به زیر مدار زمین برسانند. نخستین ماهوارهٔ فضایی ناسا نیز اکسپلورر ۱ بود که در سال ۱۹۵۸ میلادی به فضا پرتاب شد. در ۱۲ آوریل ۱۹۶۱، یوری گاگارین اهل شوروی با فضاپیمای وستوک-۱ به فضا پرتاب شد و تبدیل به نخستین انسان فضانورد جهان شد. حدود یک ماه بعد در ۵ مه، آلن شپارد با مرکوری-رادستون ۳ از پروژهٔ مرکوری به فضا پرتاب شد و تبدیل به نخستین فضانورد آمریکایی شد. در ۲۰ فوریهٔ ۱۹۶۲، جان گلن با مرکوری-اطلس ۶ به فضا پرتاب شد و در کمتر از ۵ ساعت، ۳ بار پیرامون کرهٔ زمین گردید و تبدیل به نخستین آمریکایی شد که پیرامون زمین می‌گردد. پروژهٔ جمینای نیز دستاوردهایی مانند نخستین مانور مداری، اتصال و پهلوگیری فضاپیما و نخستین راهپیمایی فضایی آمریکا به همراه داشت.

پس از پروژهٔ جمینای، ناسا پروژهٔ آپولو را راه‌اندازی کرد که این پروژه یکی از شناخته‌شده‌ترین پروژه‌های علمی تاریخ آمریکا و جهان بوده‌است. در ۲۱ ژوئیهٔ ۱۹۶۹، نیل آرمسترانگ و باز آلدرین در طول مأموریت آپولو ۱۱ بر کرهٔ ماه گام نهادند و تبدیل به نخستین انسان‌هایی شدند که بر ماه گام برمی‌دارند. طی پروژهٔ آپولو، ۱۲ فضانورد مرد بر ماه گام نهادند. پس از مأموریت آپولو ۱۷ که بازپسین سفر بشر به ماه بود، دیگر پای هیچ انسانی به ماه نرسید. اسکای‌لب نخستین ایستگاه فضایی آمریکا بود و ایستگاهی ملی بود. در سال ۱۹۷۵، ناسا و سازمان فضایی فدرال روسیه پروژه‌ای مشترک به نام پروژهٔ آزمایشی آپولو–سایوز انجام‌دادند که این پروژه نخستین مأموریت فضایی بین‌المللی بود. از سال ۱۹۸۱ تا ۲۰۱۱، ناسا پروژه‌ای به نام برنامهٔ شاتل‌های فضایی را اجرا کرد. این پروژه شامل ۱۳۵ پرواز فضایی بود و فاجعه‌های چلنجر و کلمبیا را هم به همراه داشت. ناسا در ایستگاه فضایی بین‌المللی مشارکت دارد. به غیر از ناسا، ۱۵ عضو دیگر که ۱۱ عضو از آن‌ها اعضای سازمان فضایی اروپا هستند، در این پروژهٔ بین‌المللی مشارکت دارند. افزون بر فضاپیماهای دارای سرنشین، ناسا فضاپیماهای بدون سرنشینی را نیز مانند نیوهورایزنز و مریخ‌نورد کنجکاوی به فضا پرتاب کرده‌است.

ناسا به پروژه‌های پژوهشی هم می‌پردازد. در سال ۲۰۱۴، این سازمان رقابتی سالانه با عنوان مکعب‌ها در فضا آغاز کرد. ناسا به انجام پژوهش دربارهٔ تغییر اقلیم هم مشغول است و گزارش‌هایی در این خصوص تهیه و منتشر می‌کند.

مدیر ناسا بالاترین شخص تصمیم‌گیرندهٔ این سازمان است. مدیر کنونی ناسا بیل نلسون و معاون او جیمز مورهارد است. ناسا دارای ۱۲ مرکز مانند مرکز فرماندهی ناسا و مرکز پژوهشی ایمز است. میزان بودجهٔ سالانهٔ ناسا سیر صعودی دارد. درصد این بودجه از بودجهٔ نظام فدرالی ایالات متحدهٔ آمریکا در سال ۱۹۶۶ به اوج خود (۴٫۴۱ درصد) رسید.
    </div>
{% endblock %}

templates/WebSite/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>NASA</title>
        <link rel="icon" type="image/x-icon" href="{% static 'base/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'base/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'base/css/My-css.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item" style="margin-left: 30px"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'login' %}">ورود</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'Nasa:home' %}">خانه</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'Nasa:post' %}">پست ها</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'Nasa:contact' %}">تماس با ما</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'Nasa:about' %}">درباره ما</a></li>
                    </ul>
                </div>
                <a class="navbar-brand" href="{% url 'Nasa:home' %}">NASA.IR</a>
            </div>
        </nav>
{% block Header %}
            <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'base/assets/img/Planets.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>{{ obj.Title }}</h1>
                            <span class="subheading">↓</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
{% endblock %}

{% block Main %}

{% endblock %}
        <!-- Footer-->
        <footer class="border-top" style="margin-left: 50px">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div style="margin-right: 40px" class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'base/js/scripts.js' %}"></script>
    </body>
</html>

templates/WebSite/contact.html
{% extends 'WebSite/base.html' %}
{% load static %}
{% block Header %}
            <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'base/assets/img/596263.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>تماس با ما</h1>
                            <span class="subheading">↓</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
{% endblock %}
{% block Main %}
    <h1>برای پشتیبانی با ایمیل زیر در ارتباط باشید.</h1>
    <span style="margin-top: 40px">arshia21420@gmail.com</span>
{% endblock %}

templates/WebSite/home.html
{% extends 'WebSite/base.html' %}
{% load static %}
{% block Header %}
            <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'base/assets/img/1049945.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>خانه</h1>
                            <span class="subheading">↓</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
{% endblock %}
{% block Main %}
<center style="margin-bottom: 30px">ببینید | ویدیویی عجیب از عظمت جهان که ناسا منتشر کرد</center>
<center>
    <iframe width="550" height="315" src="https://www.youtube.com/embed/2gp0sc-0ncI" title="YouTube video player" frameborder="0" allow="accelerometer;
        autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" style="border: rgba(204,6,0,0.7) 5px solid" allowfullscreen></iframe>
</center>
{% endblock %}

templates/WebSite/post.html
{% extends 'WebSite/base.html' %}
{% load static %}
{% block Header %}
            <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'base/assets/img/896199.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>پست ها</h1>
        <! –– search-bar ––>
                        <form class="inline-form" action="{% url 'Nasa:search' %}">
                                <center><input style="width: 230px; height: 30px; margin: 22px; text-align: center" type="text" name="q" class="form-control" placeholder="جستجوی متن"></center>
                                <button style="margin: 15px; padding: 14px; border-radius: 16px" class="btn btn-success">جستجو</button>
                        </form>
                            <span class="subheading">↓</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>

{% endblock %}
{% block Main %}
    <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% for obj in object_list %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'Nasa:Nasa-Detail' obj.Slug %}">
                           <center style="margin-bottom: 35px"><h1 class="post-title">{{ obj.Title }}
                               {% if obj.Is_Special %}
                                (<span style="color: red">ویژه</span>)
                            {% endif %}
                           </h1></center>
                           <center style="margin-bottom: 50px"> <img src="{{ obj.Image.url|safe }}" style="width: auto; height: 200px"> </center>
                            <h3 class="post-subtitle">{{ obj.Description|truncatewords:20|safe }}</h3>
                        </a>
                        <p class="post-meta">
                            ارسال شده توسط
                            <a href="#!">{{ obj.author.get_full_name }}</a>
                            در {{ obj.Published }}
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    {% endfor %}
                    <!-- Pager-->
                {% if page_obj.has_next %}
                    <a style="float:right; margin: 7px" class="btn btn-primary float-right" href="{% url 'Nasa:post' %}?page={{ page_obj.next_page_number }}">   → بعدی</a>
                {% endif %}

                {% if page_obj.has_previous %}
                    <a style="margin: 7px; float: left" class="btn btn-primary float-left" href="{% url 'Nasa:post' %}?page={{ page_obj.previous_page_number }}">  قبلی ←  </a>
                {% endif %}
                </div>
            </div>
        </div>

{% endblock %}

templates/WebSite/search-bar.html
{% extends 'Website/post.html' %}

{% block header %}
	<h3 class="alert alert-primary text-center">جستجو: {{search}}</h3>
{% endblock %}

{% block previous_page_url %}
	{% url 'Nasa:search' page_obj.previous_page_number %}?q={{search}}
{% endblock %}

{% block next_page_url %}
	{% url 'Nasa:search' page_obj.next_page_number %}?q={{search}}
{% endblock %}